[package]
name = "Rust_Hello_World_Hygienic_macro"
version = "0.1.0"
authors = ["lambertomaza <lmaza@ipn.mx>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
